services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 3001:3000
    depends_on: 
      - db

  db:
    image: mongo
    volumes:
      - db-data:/var/lib/mongo/data
    expose:
      - 27018:27017

volumes:
  db-data:
